
services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.4
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
      - automations_default
    environment:
      # Server
      - SERVER_URL=http://localhost:8080
      
      # Database
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution_user:evolution_password@postgres:5432/evolution_db?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_exchange
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1023204200
      
      # Redis Cache
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/1
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=false
      
      # Auth
      - AUTHENTICATION_API_KEY=B6D711FCDE4D4FD5936544120E713976
      
      # WhatsApp
      - CONFIG_SESSION_PHONE_CLIENT=Evolution API
      - CONFIG_SESSION_PHONE_NAME=Chrome

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    networks:
      - evolution-net
    ports:
      - "6379:6379"

  postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    command: ["postgres", "-c", "max_connections=1000"]
    environment:
      - POSTGRES_DB=evolution_db
      - POSTGRES_USER=evolution_user
      - POSTGRES_PASSWORD=evolution_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net
    ports:
      - "5433:5432"

networks:
  evolution-net:
    driver: bridge
  automations_default:
    external: true

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data: